version: '3.7'

services:
  emn-web:
    image: gulczyn/emn_image:v1
    container_name: EMN
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "8001:80"
    volumes:
      - .:/code
  database:
    image: mongo:latest
    container_name: emn_mongo_db
    ports:
      - "27018:27017"
    volumes:
      - emn-mongodb-data:/data/db
volumes:
  emn-mongodb-data: